
package service.location;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocationImpl", targetNamespace = "http://location.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocationImpl {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editLocation", targetNamespace = "http://location.service/", className = "service.location.EditLocation")
    @ResponseWrapper(localName = "editLocationResponse", targetNamespace = "http://location.service/", className = "service.location.EditLocationResponse")
    @Action(input = "http://location.service/LocationImpl/editLocationRequest", output = "http://location.service/LocationImpl/editLocationResponse")
    public String editLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addLocation", targetNamespace = "http://location.service/", className = "service.location.AddLocation")
    @ResponseWrapper(localName = "addLocationResponse", targetNamespace = "http://location.service/", className = "service.location.AddLocationResponse")
    @Action(input = "http://location.service/LocationImpl/addLocationRequest", output = "http://location.service/LocationImpl/addLocationResponse")
    public String addLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteLocation", targetNamespace = "http://location.service/", className = "service.location.DeleteLocation")
    @ResponseWrapper(localName = "deleteLocationResponse", targetNamespace = "http://location.service/", className = "service.location.DeleteLocationResponse")
    @Action(input = "http://location.service/LocationImpl/deleteLocationRequest", output = "http://location.service/LocationImpl/deleteLocationResponse")
    public String deleteLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
